name: GA4 Auto Add

on:
  workflow_dispatch:

jobs:
  add-ga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add Google Analytics
        run: |
          GA='<script async src="https://www.googletagmanager.com/gtag/js?id=G-4WP1H2EJ6F"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","G-4WP1H2EJ6F");</script>'
          find . -name "*.html" -type f -exec sed -i "/<head>/a $GA" {} \;
          echo "GA eklendi"

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Add GA4" || echo "No change"
          git push
